version: '2'
services:
    test3-app:
        image: test3
        external_links:
            - test3-mysql:mysql
            - test3-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    test3-mysql:
        extends:
            file: mysql.yml
            service: test3-mysql
    test3-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: test3-elasticsearch
